name: national-acts-vip
services:
  nationalactswww:
    image: nationalactsvip/nationalactswww
    container_name: nationalactswww
    networks:
      - app-network
    ports:
      - 4000:3000
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
